version: '3.8'

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: django_db
      POSTGRES_USER: django_user
      POSTGRES_PASSWORD: my_password
    ports:
      - "192.168.1.33:5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: